export const FIELD_DOCS: Record<string, string> = {
  name: 'Short title analysts recognize in the repo and in deploy output.',
  'metadata.schema': 'Which object type this file is (threat, objective, or rule).',
  'metadata.version': 'Version of this instance. Bump when you change the content.',
  'metadata.uuid': 'Stable ID used to link threats, objectives, and rules together.',
  'metadata.tlp': 'Sharing boundary (clear, green, amber, red).',
  schema: 'Object type revision — selects the Pydantic model / JSON Schema.',
  version: 'Business semver for this object instance.',
  uuid: 'Stable identifier for chaining across the object graph.',
  tlp: 'Traffic Light Protocol marking for sharing.',
  created: 'When this object was first authored.',
  modified: 'Last meaningful content change.',
  author: 'Primary author of this object.',
  detection_model: 'Objective UUID this rule implements (MDR → DOM link).',
  configurations: 'Per-platform query blocks (Sentinel, Defender, …).',
  techniques: 'MITRE ATT&CK techniques covered by this rule.',
  attack: 'ATT&CK techniques scoped on the objective.',
  'att&ck': 'ATT&CK technique IDs on the threat vector.',
  signals: 'Observable behaviours that indicate the objective is met.',
  sentinel: 'Microsoft Sentinel KQL configuration block.',
  defender_for_endpoint: 'Defender for Endpoint hunting query block.',
  query: 'Platform-native detection query text.',
  enabled: 'Whether this platform config is active for deploy.',
  criticality: 'How urgent this threat scenario is for your org.',
  composition: 'How multiple signals should combine (strategy + narrative).',
  strategy: 'Composition vocabulary — e.g. synergetic, independent.',
  threats: 'Threat vector UUIDs this objective responds to.',
  description: 'Plain-language summary of what this object represents.',
  severity: 'Impact / alert level for prioritization.',
  status: 'Lifecycle stage (e.g. STAGING before production).',
  priority: 'How urgently this objective should be covered.',
  type: 'Detection type vocabulary (e.g. Threat).',
  impact: 'Business impact vocabulary for the threat.',
  leverage: 'How much advantage the adversary gains.',
  viability: 'How realistic / likely the scenario is.',
  terrain: 'Where the threat hits — surface / terrain vocabulary.',
  killchain: 'Kill-chain stage(s) for the vector.',
  actors: 'Threat actor vocabulary values when known.',
  methodology: 'How the signal is detected (analytics, signature, …).',
  entities: 'Entity types involved in the signal (host, process, …).',
  data: 'Telemetry availability and source requirements.',
  availability: 'How complete the required data is in your estate.',
  requirements: 'Which telemetry the signal needs to fire.',
  response: 'Alert severity and analyst response guidance.',
  alert_severity: 'Severity raised to the SOC when the rule fires.',
  procedure: 'Analysis / containment steps for responders.',
  analysis: 'First-pass investigation narrative.',
  scheduling: 'How often the query runs and lookback window.',
  frequency: 'Schedule cadence (ISO-8601 duration).',
  lookback: 'How far back each run inspects.',
  alert: 'Platform-specific alert title / category.',
  references: 'External advisories and internal cross-links.',
  public: 'Public reference IDs mapped to URLs.',
  'threat.description': 'What the adversary is doing and why it matters.',
  'objective.description': 'What you want to detect and under which threat.',
};
