export const FIELD_DOCS: Record<string, string> = {
  name: 'Short title analysts recognize in the repo and in deploy output.',
  'metadata.schema': 'Which object type this file is (threat, objective, or rule).',
  'metadata.version': 'Version of this instance. Bump when you change the content.',
  'metadata.uuid': 'Stable ID used to link threats, objectives, and rules together.',
  'metadata.tlp': 'Sharing boundary (clear, green, amber, red).',
  schema: 'Object type revision.',
  version: 'Instance version.',
  uuid: 'Stable identifier for chaining.',
  tlp: 'Traffic Light Protocol marking.',
  detection_model: 'Which objective this rule implements.',
  configurations: 'Per-platform queries (Sentinel, Defender, etc.).',
  techniques: 'MITRE ATT&CK techniques this covers.',
  signals: 'Observable behaviours that indicate the objective is met.',
  sentinel: 'Microsoft Sentinel KQL block.',
  defender_for_endpoint: 'Defender for Endpoint hunting query.',
  query: 'Platform-native detection query.',
  enabled: 'Whether this platform config is active.',
  criticality: 'How urgent this threat scenario is for your org.',
  composition: 'How multiple signals should combine.',
  threats: 'Threat UUIDs this objective responds to.',
  description: 'Plain-language summary of what this object represents.',
  severity: 'Impact level for alerting and prioritization.',
  status: 'Lifecycle stage (e.g. STAGING before production).',
  'threat.description': 'What the adversary is doing and why it matters.',
  'objective.description': 'What you want to detect and under which threat.',
};
